server:
  port: 9001
  
netty: 
  server: 
    host: 222.73.119.230
    port: 9011
    
    
spring:
  redis:
    host: 192.168.1.218
    port: 6379
    database: 2
  datasource:
    url: jdbc:mysql://192.168.1.218:3306/bm?zeroDateTimeBehavior=convertToNull
    username: root
    password: da123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
     